import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Rocket, Lightbulb, Users, Target, Shield, Zap, ArrowRight, ChevronRight, ChevronLeft } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import './FeaturePage.css';

const features = [
    {
        icon: Lightbulb,
        title: 'AI-Powered Ideas',
        description: 'Get unique project ideas generated by advanced AI tailored to your skills and interests.',
        color: '#0ea5e9'
    },
    {
        icon: Target,
        title: 'Step-by-Step Guidance',
        description: 'Follow our 8-step locked journey from idea selection to final presentation.',
        color: '#3b82f6'
    },
    {
        icon: Shield,
        title: 'Uniqueness Engine',
        description: 'Prevent duplicate projects with our intelligent uniqueness checker system.',
        color: '#2563eb'
    },
    {
        icon: Users,
        title: 'Team Collaboration',
        description: 'Work solo or invite team members to collaborate seamlessly on projects.',
        color: '#60a5fa'
    },
    {
        icon: Zap,
        title: 'Smart Roadmaps',
        description: 'AI generates detailed roadmaps with milestones, timelines, and deliverables.',
        color: '#38bdf8'
    },
    {
        icon: Rocket,
        title: 'Complete Package',
        description: 'From PPT to documentation to Viva prep - everything you need in one place.',
        color: '#0284c7'
    }
];

export default function FeaturePage() {
    const [currentStep, setCurrentStep] = useState(0);
    const navigate = useNavigate();

    const handleNext = () => {
        if (currentStep < features.length - 1) {
            setCurrentStep(currentStep + 1);
        } else {
            navigate('/welcome');
        }
    };



    const feature = features[currentStep];

    return (
        <div className="feature-page">
            <button className="skip-btn" onClick={() => navigate('/welcome')}>
                Skip
            </button>

            <div className="feature-container">
                <div className="step-indicator">
                    {features.map((_, index) => (
                        <div
                            key={index}
                            className={`step-dot ${index === currentStep ? 'active' : ''} ${index < currentStep ? 'completed' : ''}`}
                        />
                    ))}
                </div>

                <AnimatePresence mode="wait">
                    <motion.div
                        key={currentStep}
                        initial={{ opacity: 0, x: 50 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: -50 }}
                        transition={{ duration: 0.4, ease: "easeOut" }}
                        className="feature-card-wrapper"
                    >
                        <div className="feature-card glass-container">
                            <div className="feature-icon-wrapper" style={{ background: `linear-gradient(135deg, white, ${feature.color}22)` }}>
                                <feature.icon size={80} color={feature.color} strokeWidth={1.5} />
                            </div>
                            <h2 className="feature-title">{feature.title}</h2>
                            <p className="feature-description">{feature.description}</p>
                        </div>
                    </motion.div>
                </AnimatePresence>

                <div className="feature-navigation">
                    <button className="nav-btn next" onClick={handleNext}>
                        {currentStep === features.length - 1 ? 'Get Started' : 'Continue'}
                        <ChevronRight size={24} />
                    </button>
                </div>
            </div>
        </div>
    );
}
